import type { Project } from "@/components/project-card";

export const projects: Project[] = [
  {
    title: "CABSHARENITR",
    description: "Ride-sharing app for the NIT Rourkela community to share cabs and fares.",
    tags: ["Next.js", "tRPC/REST", "Prisma", "Postgres", "Auth"],
    domain: "web",
    category: "scaled",
    link: "https://your-demo-link.example",
    repo: "https://github.com/your/repo",
  },
  {
    title: "Credit Risk Detection",
    description: "Supervised learning model trained on real-world bank data to assess borrower risk. Includes feature engineering, model comparison, and explainability to support underwriting decisions.",
    tags: ["Python", "Pandas", "Scikit-learn", "XGBoost", "EDA"],
    domain: "ml",
    category: "valuable",
    link: "https://your-demo-link.example",
    repo: "https://github.com/your/repo",
  },
  {
    title: "Portfolio Site",
    description: "Personal portfolio built with Next.js app router and Tailwind.",
    tags: ["Next.js", "TypeScript", "Tailwind"],
    domain: "web",
    link: "https://your-demo-link.example",
    repo: "https://github.com/your/repo",
  },
  {
    title: "Socio",
    description: "MERN stack social media app with real-time chat, notifications, and media sharing.",
    tags: ["MongoDB", "Express", "React", "Node.js","inngest","imagekit.io"],
    domain: "web",
    category: "practice",
    link: "https://your-demo-link.example",
    repo: "https://github.com/your/repo",
  },
  {
    title: "Quickshow",
    description: "Scalable movie-booking website with real-time booking and seat selection.",
    tags: ["Node.js", "React", "Express", "MongoDB"],
    domain: "web",
    category: "valuable",
    link: "https://your-demo-link.example",
    repo: "https://github.com/your/repo",
  },
  {
    title: "Movie-Recommender System",
    description: "Content-based movie recommender using NLP techniques like TF-IDF and cosine similarity to suggest movies based on user preferences.",
    tags: ["Python", "Pandas", "Scikit-learn", "Airflow"],
    domain: "ml",
    category: "valuable",
    link: "https://your-demo-link.example",
    repo: "https://github.com/your/repo",
  },
];
