export const cards = [
  {
    title: "Web Development",
    description: "Frontend architecture, design systems, and performant APIs that keep products fast and maintainable.",
    gradient: "from-sky-400/60 via-indigo-500/40 to-purple-500/40",
    techs: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Firebase",
      "PostgreSQL",
      "Framer Motion",
    ],
  },
  {
    title: "ML Engineer",
    description: "End-to-end machine learning workflows from exploration to deployment with robust monitoring.",
    gradient: "from-emerald-400/60 via-cyan-400/40 to-blue-500/35",
    techs: [
      "Python",
      "NumPy",
      "Pandas",
      "Scikit-learn",
      "TensorFlow",
      "PyTorch",
      "Matplotlib",
    ],
  },
  {
    title: "DevOps Engineer",
    description: "Reliable infrastructure, automated delivery pipelines, and observability for production systems.",
    gradient: "from-amber-400/60 via-orange-500/45 to-rose-500/40",
    techs: ["Docker", "Kubernetes", "AWS", "Terraform", "CI/CD", "Linux"],
  },
];

export const techInfo: Record<string, string> = {
  "Next.js": "React framework for SSR/SSG and app routing.",
  React: "UI library for building component-based interfaces.",
  TypeScript: "Typed superset of JavaScript for safer code.",
  "Tailwind CSS": "Utility-first CSS framework for rapid UI building.",
  "Node.js": "JavaScript runtime for building backends and tools.",
  Firebase: "Backend services: auth, firestore, hosting, storage.",
  PostgreSQL: "Open-source relational database with strong SQL support.",
  "Framer Motion": "Production-ready animation library for React.",
  Python: "General-purpose language for ML, data, and scripting.",
  NumPy: "N-dimensional arrays and numeric computing.",
  Pandas: "DataFrames and data analysis toolkit.",
  "Scikit-learn": "Classical ML algorithms and utilities.",
  TensorFlow: "Deep learning framework by Google.",
  PyTorch: "Dynamic deep learning framework by Meta.",
  Matplotlib: "Plotting library for Python.",
  Docker: "Containerization for reproducible deployments.",
  Kubernetes: "Orchestrates containers at scale.",
  AWS: "Cloud services platform for compute, storage, and more.",
  Terraform: "Infrastructure as code across multiple providers.",
  "CI/CD": "Automated build, test, and deploy pipelines.",
  Linux: "Operating system powering servers and dev environments.",
};

export const techLogos: Record<string, string | undefined> = {
  "Next.js": undefined,
  React: undefined,
  TypeScript: undefined,
  "Tailwind CSS": undefined,
  "Node.js": undefined,
  Firebase: undefined,
  PostgreSQL: undefined,
  "Framer Motion": undefined,
  Python: undefined,
  NumPy: undefined,
  Pandas: undefined,
  "Scikit-learn": undefined,
  TensorFlow: undefined,
  PyTorch: undefined,
  Matplotlib: undefined,
  Docker: undefined,
  Kubernetes: undefined,
  AWS: undefined,
  Terraform: undefined,
  "CI/CD": undefined,
  Linux: undefined,
};
