export const cards = [
  {
    title: "Web Development",
    description: "Frontend architecture, design systems, and performant APIs that keep products fast and maintainable.",
    gradient: "from-sky-400/60 via-indigo-500/40 to-purple-500/40",
    techs: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Firebase",
      "PostgreSQL",
      "Framer Motion",
    ],
  },
  {
    title: "ML Engineer",
    description: "End-to-end machine learning workflows from exploration to deployment with robust monitoring.",
    gradient: "from-emerald-400/60 via-cyan-400/40 to-blue-500/35",
    techs: [
      "Python",
      "NumPy",
      "Pandas",
      "Scikit-learn",
      "TensorFlow",
      "PyTorch",
      "Matplotlib",
    ],
  },
  {
    title: "DevOps Engineer",
    description: "Reliable infrastructure, automated delivery pipelines, and observability for production systems.",
    gradient: "from-amber-400/60 via-orange-500/45 to-rose-500/40",
    techs: ["Docker", "Kubernetes", "AWS", "Terraform", "CI/CD", "Linux"],
  },
  {
    title: "Deep Learning",
    description: "Research-grade experimentation and production-ready neural networks tailored to product objectives.",
    gradient: "from-fuchsia-400/55 via-violet-500/40 to-indigo-500/35",
    techs: ["TensorFlow", "PyTorch", "Keras", "ONNX", "Weights & Biases"],
  },
  {
    title: "MLOps",
    description: "Automated model delivery, governance, and monitoring across cloud and on-prem pipelines.",
    gradient: "from-slate-200/50 via-blue-400/40 to-emerald-400/35",
    techs: ["MLflow", "Kubeflow", "Apache Airflow", "Prefect", "SageMaker", "Great Expectations"],
  },
];

export const techInfo: Record<string, string> = {
  "Next.js": "React framework for SSR/SSG and app routing.",
  React: "UI library for building component-based interfaces.",
  TypeScript: "Typed superset of JavaScript for safer code.",
  "Tailwind CSS": "Utility-first CSS framework for rapid UI building.",
  "Node.js": "JavaScript runtime for building backends and tools.",
  Firebase: "Backend services: auth, firestore, hosting, storage.",
  PostgreSQL: "Open-source relational database with strong SQL support.",
  "Framer Motion": "Production-ready animation library for React.",
  Python: "General-purpose language for ML, data, and scripting.",
  NumPy: "N-dimensional arrays and numeric computing.",
  Pandas: "DataFrames and data analysis toolkit.",
  "Scikit-learn": "Classical ML algorithms and utilities.",
  TensorFlow: "Deep learning framework by Google.",
  PyTorch: "Dynamic deep learning framework by Meta.",
  Matplotlib: "Plotting library for Python.",
  Docker: "Containerization for reproducible deployments.",
  Kubernetes: "Orchestrates containers at scale.",
  AWS: "Cloud services platform for compute, storage, and more.",
  Terraform: "Infrastructure as code across multiple providers.",
  "CI/CD": "Automated build, test, and deploy pipelines.",
  Linux: "Operating system powering servers and dev environments.",
  Keras: "High-level neural network API running on top of deep learning frameworks.",
  ONNX: "Open format for exchanging machine learning models across frameworks.",
  "Weights & Biases": "Experiment tracking, model management, and collaboration tooling.",
  MLflow: "Open-source platform for managing the ML lifecycle and experiment metadata.",
  Kubeflow: "Kubernetes-native platform for deploying and managing ML workloads.",
  "Apache Airflow": "Workflow orchestrator for complex data and ML pipelines.",
  Prefect: "Python-first workflow orchestration with a developer-friendly API.",
  SageMaker: "AWS platform for building, training, and deploying ML models at scale.",
  "Great Expectations": "Data quality and validation framework for analytics and ML pipelines.",
};

export const techLogos: Record<string, string | undefined> = {
  "Next.js": undefined,
  React: undefined,
  TypeScript: undefined,
  "Tailwind CSS": undefined,
  "Node.js": undefined,
  Firebase: undefined,
  PostgreSQL: undefined,
  "Framer Motion": undefined,
  Python: undefined,
  NumPy: undefined,
  Pandas: undefined,
  "Scikit-learn": undefined,
  TensorFlow: undefined,
  PyTorch: undefined,
  Matplotlib: undefined,
  Docker: undefined,
  Kubernetes: undefined,
  AWS: undefined,
  Terraform: undefined,
  "CI/CD": undefined,
  Linux: undefined,
  Keras: undefined,
  ONNX: undefined,
  "Weights & Biases": undefined,
  MLflow: undefined,
  Kubeflow: undefined,
  "Apache Airflow": undefined,
  Prefect: undefined,
  SageMaker: undefined,
  "Great Expectations": undefined,
};
